@echo off
echo Starting SMP Notice Board Application...
echo.
echo Starting Backend Server (Port 3001)...
start cmd /k "cd server && npm run dev"
timeout /t 3 /nobreak >nul
echo Starting Frontend Server (Port 5173)...
start cmd /k "npm run dev"
echo.
echo Both servers are starting in separate windows...
echo Backend: http://localhost:3001
echo Frontend: http://localhost:5173
echo.
echo Press any key to exit this window...
pause >nul
