import { Department, DepartmentInfo } from '../types'

export const departmentInfo: Record<Department, DepartmentInfo> = {
  CE: {
    code: 'CE',
    name: 'Civil Engineering',
    color: '#3B82F6',
    lightColor: '#EFF6FF',
    bgClass: 'bg-ce-light',
    textClass: 'text-ce',
    borderClass: 'border-ce',
  },
  ME: {
    code: 'ME',
    name: 'Mechanical Engineering',
    color: '#10B981',
    lightColor: '#ECFDF5',
    bgClass: 'bg-me-light',
    textClass: 'text-me',
    borderClass: 'border-me',
  },
  CS: {
    code: 'CS',
    name: 'Computer Science',
    color: '#8B5CF6',
    lightColor: '#F5F3FF',
    bgClass: 'bg-cs-light',
    textClass: 'text-cs',
    borderClass: 'border-cs',
  },
  EC: {
    code: 'EC',
    name: 'Electronics & Communication',
    color: '#F97316',
    lightColor: '#FFF7ED',
    bgClass: 'bg-ec-light',
    textClass: 'text-ec',
    borderClass: 'border-ec',
  },
  EE: {
    code: 'EE',
    name: 'Electrical Engineering',
    color: '#EF4444',
    lightColor: '#FEF2F2',
    bgClass: 'bg-ee-light',
    textClass: 'text-ee',
    borderClass: 'border-ee',
  },
  All: {
    code: 'All',
    name: 'All Departments',
    color: '#6B7280',
    lightColor: '#F9FAFB',
    bgClass: 'bg-all-light',
    textClass: 'text-all',
    borderClass: 'border-all',
  },
  Office: {
    code: 'Office',
    name: 'Office',
    color: '#06B6D4',
    lightColor: '#ECFEFF',
    bgClass: 'bg-cyan-50',
    textClass: 'text-cyan-600',
    borderClass: 'border-cyan-600',
  },
  Results: {
    code: 'Results',
    name: 'Results',
    color: '#84CC16',
    lightColor: '#F7FEE7',
    bgClass: 'bg-lime-50',
    textClass: 'text-lime-600',
    borderClass: 'border-lime-600',
  },
  'Fee Dues': {
    code: 'Fee Dues',
    name: 'Fee Dues',
    color: '#F59E0B',
    lightColor: '#FEF3C7',
    bgClass: 'bg-amber-50',
    textClass: 'text-amber-600',
    borderClass: 'border-amber-600',
  },
  Exams: {
    code: 'Exams',
    name: 'Exams',
    color: '#DC2626',
    lightColor: '#FEE2E2',
    bgClass: 'bg-red-50',
    textClass: 'text-red-600',
    borderClass: 'border-red-600',
  },
  Scholarships: {
    code: 'Scholarships',
    name: 'Scholarships',
    color: '#16A34A',
    lightColor: '#F0FDF4',
    bgClass: 'bg-green-50',
    textClass: 'text-green-600',
    borderClass: 'border-green-600',
  },
  Internship: {
    code: 'Internship',
    name: 'Internship',
    color: '#7C3AED',
    lightColor: '#F5F3FF',
    bgClass: 'bg-violet-50',
    textClass: 'text-violet-600',
    borderClass: 'border-violet-600',
  },
  'Annual Day': {
    code: 'Annual Day',
    name: 'Annual Day',
    color: '#EC4899',
    lightColor: '#FCE7F3',
    bgClass: 'bg-pink-50',
    textClass: 'text-pink-600',
    borderClass: 'border-pink-600',
  },
  Functions: {
    code: 'Functions',
    name: 'Functions',
    color: '#8B5CF6',
    lightColor: '#FAF5FF',
    bgClass: 'bg-purple-50',
    textClass: 'text-purple-600',
    borderClass: 'border-purple-600',
  },
  'Admission Ticket': {
    code: 'Admission Ticket',
    name: 'Admission Ticket',
    color: '#14B8A6',
    lightColor: '#F0FDFA',
    bgClass: 'bg-teal-50',
    textClass: 'text-teal-600',
    borderClass: 'border-teal-600',
  },
  Admissions: {
    code: 'Admissions',
    name: 'Admissions',
    color: '#0EA5E9',
    lightColor: '#F0F9FF',
    bgClass: 'bg-sky-50',
    textClass: 'text-sky-600',
    borderClass: 'border-sky-600',
  },
  'Red Cross': {
    code: 'Red Cross',
    name: 'Red Cross',
    color: '#DC2626',
    lightColor: '#FEE2E2',
    bgClass: 'bg-red-50',
    textClass: 'text-red-600',
    borderClass: 'border-red-600',
  },
  NSS: {
    code: 'NSS',
    name: 'NSS',
    color: '#0891B2',
    lightColor: '#ECFEFF',
    bgClass: 'bg-cyan-50',
    textClass: 'text-cyan-700',
    borderClass: 'border-cyan-700',
  },
}

export const departments: Department[] = ['Admission Ticket', 'Admissions', 'All', 'Annual Day', 'CE', 'CS', 'EC', 'EE', 'Exams', 'Fee Dues', 'Functions', 'Internship', 'ME', 'NSS', 'Office', 'Red Cross', 'Results', 'Scholarships']
